
const Data2 =  {
  ip: "196.249.93.101",
  continent_code: "AF",
  continent_name: "Africa",
  country_code2: "TZ",
  country_code3: "TZA",
  country_name: "Tanzania",
  country_name_official: "United Republic of Tanzania",
  country_capital: "Dodoma",
  state_prov: "Dar es Salaam",
  state_code: "TZ-02",
  district: "Kinondoni",
  city: "Dar es Salaam",
  zipcode: "11107",
  latitude: "-6.81651",
  longitude: "39.28944",
  is_eu: false,
  country_flag: "https://ipgeolocation.io/static/flags/tz_64.png",
  geoname_id: "10228434",
  country_emoji: "🇹🇿",
  calling_code: "+255",
  country_tld: ".tz",
  languages: "sw-TZ,en,ar",
  isp: "Viettel Tanzania PLC",
  connection_type: "",
  organization: "Viettel Tanzania PLC",
  currency: {
    code: "TZS",
    name: "Tanzanian Shilling",
    symbol: "TSh",
  },
  time_zone: {
    name: "Africa/Dar_es_Salaam",
    offset: 3,
    offset_with_dst: 3,
    current_time: "2025-06-06 04:13:18.582+0300",
    current_time_unix: 1749172398.582,
    is_dst: false,
    dst_savings: 0,
    dst_exists: false,
    dst_start: "",
    dst_end: "",
  },
}

